# Generated by Django 2.2.5 on 2019-09-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='id',
        ),
        migrations.AlterField(
            model_name='iddocuments',
            name='id_type',
            field=models.CharField(choices=[('Passport', 'Passport'), ('National Id', 'National Id'), ('Iqama', 'Iqama')], max_length=25),
        ),
        migrations.AlterField(
            model_name='members',
            name='id_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='memberships.IdDocuments'),
        ),
    ]
